### PR TITLE
Fix signature algorithm name

### PR DESCRIPTION
**Pull request by MicrovisionCLG**
Using KeyHostAlgorithm.Name as a SignatureKeyData.AlgorithmName would result in a "ssh-ed25519-cert-v01@openssh.com" algorithm name while the "ssh-ed25519" one is expected.

### CODE REVIEW

**Comment by MicrovisionCLG** [comment]
Hi,
While I continue to use this certificates branch, I faced a similar problem with RSA keys : "ssh-rsa" algorithm name is used instead of "rsa-sha2-256" or "rsa-sha2-512".
Using a regular expression to remove the "cert" part from the name seems to solve the problem for both Ed25519 & RSA keys.
What do you think ?

**Comment by Rob-Hague** [comment]
Thanks for taking a look! I'll get myself reacquainted with this branch and get back to you over the weekend

**Comment by Rob-Hague** [comment]
So I had a look, I think it's something we should treat in CertificateHostAlgorithm. I want to write a couple of integration tests to make sure it is actually functional. I'll be a few more days with that

**Comment by Rob-Hague** [comment]
I wrote a couple of integration tests for the authentication, moved this code to CertificateHostAlgorithm and confirmed the tests pass with this change. Thanks! Perhaps you could try it out and report back?

Still TODO: integration tests for server certificates

Also fyi @kakins

**Comment by kakins** [comment]
Sorry, I had noble intentions here but life and other unrelated priorities quickly overtook me.  Would like to come back this at some point when I can.

**Comment by Rob-Hague** [comment]
No worries, the branch is basically complete now I'm just slowly adding polish then I'll submit upstream

**Pull request merged**
